module.exports = {
	actionConst: {
		SET_USER_CURRENT_INPUT: 'SET_USER_CURRENT_INPUT',
		SUBMIT_USER_INPUT: 'SUBMIT_USER_INPUT',
		NEW_LOG_ENTRY: 'NEW_LOG_ENTRY',
		SEND_COMMAND: 'SEND_COMMAND',
		INVALID_COMMAND: 'INVALID_COMMAND',
		NEW_USER: 'NEW_USER',
		USER_HIT: 'USER_HIT',
		USER_SPLIT: 'USER_SPLIT',
		USER_DOUBLE: 'USER_DOUBLE',
		USER_HOLD: 'USER_HOLD',
		UPDATE_USERS: 'UPDATE_USERS',
		UPDATE_USER: 'UPDATE_USER',
		USER_MESSAGE_CHANGE: 'USER_MESSAGE_CHANGE',
		USER_MESSAGE_SUBMIT: 'USER_MESSAGE_SUBMIT',
		UPDATE_MESSAGE_LOGS: 'UPDATE_MESSAGE_LOGS',
		USER_PLACE_BET: 'USER_PLACE_BET',
		GAME_PHASE_CHANGE: 'GAME_PHASE_CHANGE',
		ASSIGN_ID: 'ASSIGN_ID',
		UPDATE_CURRENT_USER_ID: 'UPDATE_CURRENT_USER_ID',
		UPDATE_DEALER: 'UPDATE_DEALER',
	},
	commandNames: {
		EAT: 'eat',
		SAY: 'say',
		CLEAR: 'clear',
	}
}
